
services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config.json:/app/config.json
      - ./certs:/app/certs
    restart: always
    networks:
      - proxy

networks:
  proxy:
    external: true